/**
 * Every logo file in public/brand, laid out so each one is legible.
 *
 * Three families — the mark on its own, the mark with its ring and name,
 * and the wordmark — in five colourways each. The mark and wordmark are
 * generated by scripts/build-brand-assets.mjs; the logo files are the
 * designer's originals.
 *
 * Each tile picks its background from the variant, not the theme: a bog
 * logo needs limestone behind it and a white one needs bog, or you are
 * looking at an empty box.
 */

const FAMILIES = [
  {
    name: "Mark",
    note: "Triskele with the tricolour set into its border. Favicons, avatars, anywhere too small for the name.",
    prefix: "",
    variants: ["color", "green", "orange", "bog", "white"],
  },
  {
    name: "Logo",
    note: "Mark, ring and name. The default.",
    prefix: "logo_",
    variants: ["color", "green", "orange", "bog", "white"],
  },
  {
    name: "Wordmark",
    note: "The horizontal lockup. Wide, shallow spaces.",
    prefix: "wordmark_",
    variants: ["color", "green", "orange", "bog", "white"],
  },
]

/** which ground each colourway needs to be readable on */
const GROUND: Record<string, { cls: string; label: string }> = {
  color: { cls: "bg-bog", label: "on bog" },
  white: { cls: "bg-bog", label: "on bog" },
  green: { cls: "bg-limestone", label: "on limestone" },
  orange: { cls: "bg-limestone", label: "on limestone" },
  bog: { cls: "bg-limestone", label: "on limestone" },
}

const Tile = ({ file, variant }: { file: string; variant: string }) => {
  const ground = GROUND[variant]
  return (
    <figure className="min-w-0">
      <div
        className={`flex aspect-square items-center justify-center border border-line p-4 ${ground.cls}`}
      >
        <img
          src={`${import.meta.env.BASE_URL}brand/${file}.svg`}
          alt={`${file} logo variant`}
          loading="lazy"
          className="max-h-full max-w-full"
        />
      </div>
      <figcaption className="mt-2 font-mono text-[10px] uppercase tracking-[0.14em] text-sub">
        {variant} · {ground.label}
      </figcaption>
    </figure>
  )
}

export const LogoVariants = () => (
  <div className="space-y-10">
    {FAMILIES.map((family) => (
      <div key={family.name}>
        <p className="font-display text-lg font-bold uppercase tracking-[0.03em]">
          {family.name}
        </p>
        <p className="mt-0.5 text-sm text-sub">{family.note}</p>
        <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">
          {family.variants.map((variant) => (
            <Tile
              key={variant}
              file={`${family.prefix}${variant}`}
              variant={variant}
            />
          ))}
        </div>
      </div>
    ))}
  </div>
)
